# Generated by Django 4.0 on 2022-01-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_friend_user1_alter_friend_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='kind',
        ),
    ]
