# Generated by Django 4.0 on 2022-01-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_connection_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
