# Generated by Django 4.0 on 2022-01-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recever_group',
            new_name='sender_group',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='recever_user',
            new_name='sender_user',
        ),
    ]
