# Generated by Django 4.0 on 2022-01-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.group'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recever', to='Accounts.useraccount'),
        ),
    ]
