# Generated by Django 4.0 on 2022-01-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_notification_sender_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='key',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
