# Generated by Django 4.0 on 2022-01-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_useraccount_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_state',
            field=models.BooleanField(default=True),
        ),
    ]
