# Generated by Django 4.0 on 2022-02-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_alter_user_in_group_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='picture',
            field=models.ImageField(default='static/image/group/groupImage.png', upload_to='static/image/group'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='picture',
            field=models.ImageField(default='static/image/user/userImage.png', upload_to='static/image/user'),
        ),
    ]
