# Generated by Django 4.0 on 2022-02-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_group_picture_useraccount_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='normal', max_length=30),
        ),
    ]
