# Generated by Django 4.0 on 2022-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='end_Reque_Call',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='name_sender',
            field=models.CharField(default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(default='you have a notification', max_length=155),
        ),
    ]
